version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore .\source\
build:
  project: source\RandomQuotes.sln
  publish_wap_octopus: true
  verbosity: minimal
deploy:
- provider: Octopus
  push_packages: true
  create_release: true
  deploy_release: true
  server: https://willitdeployepisode6.tentaclearmy.com:8085/
  api_key:
    secure: O+WRMqY79U0X6sJGYk1qNTUq37Tv8RVMFXOXKVkQqy8=
  project: '"Random Quotes"'
  release_number: %APPVEYOR_BUILD_NUMBER%
  environment: Dev
